const CHARACTER_STATS = [
  {
    id: 'patk',
    name: 'Physical Attack Power',
    description: 'Physical Attack Power is a measure of your offensive capabilities when using Physical type attacks. This stat is the base value used in all forms of Physical damage calculations.',
    max: 'N/A',
  },
  {
    id: 'matk',
    name: 'Magical Attack Power',
    description: 'Magical Attack Power is a measure of your offensive capabilities when using Magical type attacks. This stat is the base value used in all forms of Magical damage calculations.',
    max: 'N/A',
  },
  {
    id: 'mp',
    name: 'MP',
    description: 'MP, also known as Mana Points, is a measure of your character\'s maximum MP. MP is required in order to use most skills and certain commands, as well as to Mana Break.',
    max: 'N/A',
  },
  {
    id: 'crit-chance',
    name: 'Critical Chance',
    description: 'Critical grants your attacks a chance to trigger a critical hit, which will increase their damage. When a critical hit is triggered, the resulting damage numbers will be colored red instead of yellow. By default, Critical hits deal 150% damage.',
    max: '100%',
  },
  {
    id: 'crit-damage',
    name: 'Critical Damage',
    description: 'Determines the amount of damage inflicted by Critical hits, enabling you to increase it beyond the default 150%.',
    max: 'N/A',
  },
  {
    id: 'maximize',
    name: 'Maximize',
    description: 'This stat that raises the lower limit of a character\'s Physical/Magical Attack Power range. During damage calculation, this stat can also give a chance of using the maximum value of the attack power\'s upper limit.  If the character is not equipped with a weapon, Maximize will have no effect. If a character possesses 50% Maximize, they will be able to do damage equal to or greater than the listed attack power of their equipped weapon. If they possess 100% Maximize, their attack power will always be equal to the upper limit of their Attack range.',
    max: '100%',
  },
  {
    id: 'add-damage',
    name: 'Additional Damage',
    description: 'Also known as Add. Damage, this stat provides extra damage to attacks after normal damage calculation. The damage added by this stat is not affected by critical hit multipliers and is dependent on the damage percentage of the skill or command used.',
    max: '102.5%',
  },
  {
    id: 'damage-to-boss',
    name: 'Damage Increase to Boss Monsters',
    description: 'Increases the amount of damage dealt to boss monsters. This effect will add a percentage of extra attack damage when fighting bosses, however it will not affect mini-bosses or normal mobs.',
    max: 'N/A',
  },
  {
    id: 'attack/attacked',
    name: 'Polarize: Damage Dealt/Received Increased',
    description: 'Also known as Attack/Attacked Damage, this stat will increase your attack power by a specified amount, however it will also cause you to receive an equivalent amount of extra damage when you are attacked by enemies, making it a double-edged sword.',
    max: '45%',
  },
  {
    id: 'command-attack',
    name: 'Command Attack Damage Increase',
    description: 'This stat will increase the attack power of your basic commands.',
    max: 'N/A',
  },
  {
    id: 'active-skill',
    name: 'Active Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using Active Skills.',
    max: 'N/A',
  },
  {
    id: 'tenacity-skill',
    name: 'Tenacity Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using Tenacity Skills.',
    max: 'N/A',
  },
  {
    id: 'strength-skill',
    name: 'Strength Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using Strength Skills.',
    max: 'N/A',
  },
  {
    id: 'bravery-skill',
    name: 'Bravery Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using Bravery Skills.',
    max: 'N/A',
  },
  {
    id: 'hyperactive-skill',
    name: 'Hyperactive Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using Hyper Active Skills.',
    max: 'N/A',
  },
  {
    id: 'all-skill',
    name: 'All Skill Damage Increase',
    description: 'Increases the amount of damage dealt when using any skill.',
    max: 'N/A',
  },
  {
    id: 'ignore-physical-defense',
    name: 'Ignore Enemy Physical Defense',
    description: 'Ignores your enemies Physical Defense Power by a certain percentage.',
    max: '20%',
  },
  {
    id: 'ignore-magical-defense',
    name: 'Ignore Enemy Magical Defense',
    description: 'Ignores your enemies Magical Defense Power by a certain percentage.',
    max: '20%',
  },
  {
    id: 'action-speed',
    name: 'Action Speed',
    description: 'Action Speed increases the animation speed of attacks, entering Awakening Mode, and idle animations.',
    max: '130%',
  },
  {
    id: 'mp-cost-decrease',
    name: 'Skill MP Cost Decrease',
    description: 'Lowers the MP cost of using all skills.',
    max: '35%',
  },
  {
    id: 'mp-recovery-on-attack',
    name: 'MP Recovery when attacking Increase',
    description: 'Increases the amount of MP gained upon attacking enemies.',
    max: '50%',
  },
  {
    id: 'mp-recovery-when-attacked',
    name: 'MP Recovery when attacked Increase',
    description: 'Increases the amount of MP gained upon being attacked by enemies.',
    max: '50%',
  },
  {
    id: 'active-skill-cooldown',
    name: 'Active Skill Cooldown Decrease',
    description: 'Decreases the cooldown time for Active Skills.',
    max: '35%',
  },
  {
    id: 'tenacity-skill-cooldown',
    name: 'Tenacity Skill Cooldown Decrease',
    description: 'Decreases the cooldown time for Tenacity Skills.',
    max: '35%',
  },
  {
    id: 'strength-skill-cooldown',
    name: 'Strength Skill Cooldown Decrease',
    description: 'Decreases the cooldown time for Strength Skills.',
    max: '35%',
  },
  {
    id: 'bravery-skill-cooldown',
    name: 'Bravery Skill Cooldown Decrease',
    description: 'Decreases the cooldown time for Bravery Skills.',
    max: '35%',
  },
  {
    id: 'awakening-charge',
    name: 'Awakening Charge Speed Increase / DP Gain',
    description: 'Increases the rate of charging the Awakening Gauge. Normally, dealing 100 hits or receiving 50 hits is needed to charge the gauge for one Awakening Bead. Increasing this stat will increase the value of each hit dealt and received, thus decreasing the number of hits needed.  For players playing Add, this stat is replaced with the DP Gain stat, which functions similarly by increasing the rate at which Add gains DP when attacking or being attacked.',
    max: '50%',
  },
  {
    id: 'awakening-duration',
    name: 'Awakening Duration Increase / DP Cost',
    description: 'Increases the duration of the player\'s Awakening.  For players playing Add, this stat is replaced with the DP Cost stat, which lowers the rate at which Add consumes DP when attacking or entering Dynamo Configuration Mode.',
    max: '50%',
  },
  {
    id: 'hp',
    name: 'HP',
    description: 'HP, also known as Hit Points is the amount of life your character has. When your character\'s HP reaches 0, they will faint in battle, requiring you to revive if applicable, retry, or exit. If this happens in PvP, you will lose the battle. Having higher HP means you can endure more hits and survive much longer in battle.',
    max: '50%',
  },
  {
    id: 'pdef',
    name: 'Physical Defense Power',
    description: 'Physical Defense Power measures your defensive capabilities when enduring Physical-based attacks, reducing the amount of physical damage taken by a certain percentage.',
    max: 'N/A',
  },
  {
    id: 'mdef',
    name: 'Magical Defense Power',
    description: 'Magical Defense Power measures your defensive capabilities when enduring Magical-based attacks, reducing the amount of magical damage taken by a certain percentage.',
    max: 'N/A',
  },
  {
    id: 'damage-reduction',
    name: 'Damage Reduction',
    description: 'Damage Reduction, sometimes referred to as Red. Damage, absorbs the amount of damage taken by a certain percentage.',
    max: '45%',
  },
  {
    id: 'damage-from-boss',
    name: 'Damage Decrease from Boss Monsters',
    description: 'Decreases the amount of damage endured when attacked by bosses. This stat does not affect mini-bosses or normal mobs.',
    max: '45%',
  },
  {
    id: 'recovery-effect',
    name: 'Recovery Item Effect Increase',
    description: 'Increases the effectiveness of consumable recovery items.',
    max: 'N/A',
  },
]

export default CHARACTER_STATS
