const elsword = [
  {
    name: 'Elsword',
    $char_id: '01',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Felsword.png?alt=media&token=590001bd-3af0-403c-a578-8e2e3b713e32',
    characterPath: 0,
  },
  {
    name: 'Sword Knight',
    $char_id: '01.101',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsword-knight.png?alt=media&token=800e5e6f-7bbd-4b81-8fed-946d05be895a',
    characterPath: 1,
  },
  {
    name: 'Lord Knight',
    $char_id: '01.102',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Flord-knight.png?alt=media&token=da9f6b22-4899-4f15-9c04-6028e3bbe912',
    characterPath: 2,
  },
  {
    name: 'Lord Knight (T)',
    $char_id: '01.10T',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Flord-knight-trans.png?alt=media&token=625697f8-1bf5-4656-bb26-5bdb18c65bc3',
    characterPath: 3,
  },
  {
    name: 'Knight Emperor',
    $char_id: '01.103',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fknight-emperor.png?alt=media&token=f61d4722-9fad-4365-ad84-e396aa597156',
    characterPath: 4,
  },
  {
    name: 'Magic Knight',
    $char_id: '01.201',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fmagic-knight.png?alt=media&token=2ba86346-23d0-4a7e-91a2-a1faeb6e3dac',
    characterPath: 1,
  },
  {
    name: 'Rune Slayer',
    $char_id: '01.202',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-slayer.png?alt=media&token=87e4489c-f8e9-490b-be6e-3cb8cf9d7a25',
    characterPath: 2,
  },
  {
    name: 'Rune Slayer (T)',
    $char_id: '01.20T',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-slayer-trans.png?alt=media&token=694be52f-c73f-4097-9d53-3187de5f06ee',
    characterPath: 3,
  },
  {
    name: 'Rune Master',
    $char_id: '01.203',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-master.png?alt=media&token=15496cf6-ad41-4b12-9c36-5b721967473b',
    characterPath: 4,
  },
  {
    name: 'Sheath Knight',
    $char_id: '01.301',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsheath-knight.png?alt=media&token=8a10fbce-e018-490b-8027-90cd42b881e1',
    characterPath: 1,
  },
  {
    name: 'Infinity Sword',
    $char_id: '01.302',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Finfinity-sword.png?alt=media&token=7905c1fd-3f63-4fd9-af42-164cc8399b55',
    characterPath: 2,
  },
  {
    name: 'Infinity Sword (T)',
    $char_id: '01.30T',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Finfinity-sword-trans.png?alt=media&token=ad4b1baf-b75f-480f-900f-957f8530e2be',
    characterPath: 3,
  },
  {
    name: 'Immortal',
    $char_id: '01.303',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fimmortal.png?alt=media&token=4b0c3fbf-30e9-4c24-bab0-cc5078a63d4c',
    characterPath: 4,
  },
  {
    name: 'Root Knight',
    $char_id: '01.401',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Froot-knight.png?alt=media&token=675a9874-725b-4c53-9efb-d04a874e0b9a',
    characterPath: 1,
  },
  {
    name: 'Sacred Templar',
    $char_id: '01.402',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsacred-templar.png?alt=media&token=c9320eac-4912-42ad-b31f-df96f72ee56e',
    characterPath: 2,
  },
  {
    name: 'Sacred Templar (T)',
    $char_id: '01.40T',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsacred-templar-trans.png?alt=media&token=b7e00465-4375-4576-9b3d-f7950521d932',
    characterPath: 3,
  },
  {
    name: 'Genesis',
    $char_id: '01.403',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fgenesis.png?alt=media&token=9f7b734a-d5ad-453b-8389-4dc69aa569e3',
    characterPath: 4,
  },
]

export default elsword
