const firstClass = [
  {
    name: 'Sword Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsword-knight.png?alt=media&token=800e5e6f-7bbd-4b81-8fed-946d05be895a',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Magic Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fmagic-knight.png?alt=media&token=2ba86346-23d0-4a7e-91a2-a1faeb6e3dac',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Sheath Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsheath-knight.png?alt=media&token=8a10fbce-e018-490b-8027-90cd42b881e1',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'Root Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Froot-knight.png?alt=media&token=675a9874-725b-4c53-9efb-d04a874e0b9a',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 4,
  },
  {
    name: 'High Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fhigh-magician.png?alt=media&token=1d92ff19-3f80-496c-b7ff-ce304ed5430d',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Dark Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fdark-magician.png?alt=media&token=8a4ebb8a-ed19-4e96-ae84-5bdbbcb4ee4c',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Battle Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fbattle-magician.png?alt=media&token=3c9810b8-0f88-4e2b-a098-a293577c8994',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'Combat Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fcombat-ranger.png?alt=media&token=a24e9307-7c63-4b14-a605-0a69cfe7f556',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Sniping Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fsniping-ranger.png?alt=media&token=8b4a7875-fdc8-46f8-8acf-bdd413f89283',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Trapping Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Ftrapping-ranger.png?alt=media&token=920b086b-0a02-46e4-87f0-12f75a18299b',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 3,
  },
]
