const secondClass = [
  {
    name: 'Lord Knight (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Flord-knight-trans.png?alt=media&token=625697f8-1bf5-4656-bb26-5bdb18c65bc3',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Rune Slayer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-slayer-trans.png?alt=media&token=694be52f-c73f-4097-9d53-3187de5f06ee',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Infinity Sword (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Finfinity-sword-trans.png?alt=media&token=ad4b1baf-b75f-480f-900f-957f8530e2be',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Sacred Templar (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsacred-templar-trans.png?alt=media&token=b7e00465-4375-4576-9b3d-f7950521d932',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 4,
  },
  {
    name: 'Elemental Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Felemental-master-trans.png?alt=media&token=3f150e4a-57ad-4e57-abbb-51dfc77bd71f',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Void Princess (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fvoid-princess-trans.png?alt=media&token=d6a75ae9-94a2-4cd1-bcfa-99a172332f7f',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Dimension Witch (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fdimension-witch-trans.png?alt=media&token=3aba92d1-6418-42f6-afba-964a687c1bb5',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Wind Sneaker (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fwind-sneaker-trans.png?alt=media&token=17eb0ebe-2293-4dbb-bf24-ee2abb1b59c4',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Grand Archer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fgrand-archer-trans.png?alt=media&token=28934e81-a65e-420a-be1a-8cdf7e2179f4',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Night Watcher (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fnight-watcher-trans.png?alt=media&token=57f1089f-835a-4707-b493-bb3c4b3565bb',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Blade Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fblade-master-trans.png?alt=media&token=7813a963-4a5c-4d92-9a9a-704aa34555dc',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Reckless Fist (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Freckless-fist-trans.png?alt=media&token=0123d1ce-7cc2-4e87-a47c-c2107e059cd2',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Veteran Commander (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fveteran-commander-trans.png?alt=media&token=e33a0696-32a8-41aa-987f-e2697d53ec90',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Code: Nemesis (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-nemesis-trans.png?alt=media&token=ca65c85a-95f1-4970-804c-89be31ed46fa',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Code: Empress (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-empress-trans.png?alt=media&token=b6ea096f-46e8-4d62-8fc1-42bbe8b6c0ec',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Code: Battle Seraph (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-battle-seraph-trans.png?alt=media&token=563c9872-0469-44da-9c04-9e8594a49277',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Code: Failess (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-failess-trans.png?alt=media&token=5c6eef8b-04ee-4a2e-905c-b2c4dbca1d9b',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 4,
  },
  {
    name: 'Iron Paladin (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Firon-paladin-trans.png?alt=media&token=6c01b7c1-ab41-41be-9803-31d97648dab8',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Deadly Chaser (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fdeadly-chaser-trans.png?alt=media&token=1c812261-21f3-41d1-baef-fc136dcc0e80',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Tactical Trooper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Ftactical-trooper-trans.png?alt=media&token=bf20e022-d3ff-4e46-941d-b18a058780cb',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Sakra Devanam (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fsakra-devanam-trans.png?alt=media&token=ee671f27-74c0-47e5-b00c-c4f29d4e0604',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Yama Raja (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fyama-raja-trans.png?alt=media&token=410e3fde-2aa5-42f6-a80b-d09cba449b19',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Asura (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fasura-trans.png?alt=media&token=ef721814-c767-4784-aad6-0df0981c9383',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Grand Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fgrand-master-trans.png?alt=media&token=b9651045-fe20-4044-a19e-5bb97e8f70f0',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Blazing Heart (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fblazing-heart-trans.png?alt=media&token=1fc8b6ad-e4d8-41d9-b34b-f5d364fd8641',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Crimson Avenger (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fcrimson-avenger-trans.png?alt=media&token=3ae987b7-a631-44c0-8c71-a66babf98dd3',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Lunatic Psyker (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Flunatic-psyker-trans.png?alt=media&token=53a59b0d-8b9b-4fc1-aaf7-7b46572cbe68',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Mastermind (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fmastermind-trans.png?alt=media&token=87cda009-fdc6-4126-8b86-dfefc92cf6f8',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Diabolic Esper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fdiabolic-esper-trans.png?alt=media&token=2d5af881-9c43-4420-91d1-feff67ab1e1c',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Noblesse (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fnoblesse-trans.png?alt=media&token=b16e53eb-3e60-464d-b07b-cfdcafae6d4d',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Diabla (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdiabla-trans.png?alt=media&token=ffdd3ada-36e7-4771-9667-e729b298ceec',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Dreadlord (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdreadlord-trans.png?alt=media&token=ba8dbff7-87bf-4483-916e-a3938622dcdd',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Royal Guard (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Froyal-guard-trans.png?alt=media&token=621543f2-0bca-452c-9ced-89a2ee8a6d31',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Demonio (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdemonio-trans.png?alt=media&token=4f5a201e-fc97-416a-89cb-f53728c792ae',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Storm Trooper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fstorm-trooper-trans.png?alt=media&token=83d78400-fdd8-49ca-9f85-5427ed9e5b37',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Crimson Rose (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fcrimson-rose-trans.png?alt=media&token=0242b5ba-82a6-4cfa-8217-fb20dacb68f3',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Freyja (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Ffreyja-trans.png?alt=media&token=bf17559b-56e2-4ff9-ac02-5091202109b4',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Optimus (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Foptimus-trans.png?alt=media&token=5b1f9adb-fee0-4c1a-9cde-d86e7bdadbbc',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 4,
  },
  {
    name: 'Arme Thaumaturgy (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Farme-thaumaturgy-trans.png?alt=media&token=c6731175-b991-413c-9a14-b0736c723dd6',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Erbluhen Emotion (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Ferbluhen-emotion-trans.png?alt=media&token=e53f43df-2781-4c88-8e7a-d9a179876511',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Apostasia (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fapostasia-trans.png?alt=media&token=ec294a80-cee7-402d-ac71-0ce3149b56e0',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Rumble Pumn (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Frumble-pumn-trans.png?alt=media&token=b38f9e35-fb82-48f8-ba4d-c9f933284ead',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Shinning Romantica (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fshining-romantica-trans.png?alt=media&token=e90a525d-89a4-445b-9d44-97432b4875e3',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Daydreamer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fdaydreamer-trans.png?alt=media&token=f6f7b203-719f-4f04-995f-f56763519a74',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Silent Shadow (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsilent-shadow-trans.png?alt=media&token=03a14668-6cac-416d-a7de-df02000da072',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Stellar Caster (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fstellar-caster-trans.png?alt=media&token=b90f5ed0-2766-465b-9baa-065653d06178',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Pale Pilgrim (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fpale-pilgrim-trans.png?alt=media&token=5db7d600-db23-4f15-8ab8-ed71bf34959d',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 3,
  },
]

export default secondClass
